### ISSUE TITLE
Поддержка других стандартных типов кнопок

### ISSUE THREAD

**Issue by DiSonDS** [KotRikD/vk_keyboard_generator#1]
TODO:
- [x] Location
- [x] VK Pay
- [x] VK Apps

[Документация](https://vk.com/dev/bots_docs_3?f=4.%2B%D0%9A%D0%BB%D0%B0%D0%B2%D0%B8%D0%B0%D1%82%D1%83%D1%80%D1%8B%2B%D0%B4%D0%BB%D1%8F%2B%D0%B1%D0%BE%D1%82%D0%BE%D0%B2)

**Comment by KotRikD** [comment]
#2
